bgp_global:
    as_number: '65001'
    neighbor:
    -   ebgp_multihop:
            set: true
        neighbor_address: 10.200.200.1
        remote_as: '65000'
    redistribute:
    -   ospf_route: external
        protocol: ospf
    router_id: 192.168.2.2
