bgp_global:
    as_number: '65000'
    bgp:
        default:
            ipv4_unicast: true
            route_target:
                filter: true
        log_neighbor_changes: true
        router_id:
            address: 192.168.1.1
    neighbors:
    -   neighbor_address: 10.200.200.2
        remote_as: '65001'
